/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("keyforge.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":common"))
}

application {
    // Define the main class for the application.
    mainClass.set("keyforge.keyforge.AppKt")
}
