/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("keyforge.kotlin-library-conventions")
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("maven-publish")

    kotlin("plugin.serialization") version "2.0.0"
}

group = "cloud.keyforge"
version = "0.0.3"

dependencies {
    implementation("org.apache.commons:commons-text")
//    implementation(project(":common"))

    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")
    api("com.google.code.gson:gson:2.11.0")
}



publishing {
    repositories {
        maven {
            name = "flyte-repository"
            url = uri(
                "https://repo.flyte.gg/${
                    if (version.toString().endsWith("-SNAPSHOT")) "snapshots" else "releases"
                }"
            )
            credentials {
                username = System.getenv("MAVEN_NAME") ?: property("mavenUser").toString()
                password = System.getenv("MAVEN_SECRET") ?: property("mavenPassword").toString()
            }
        }
    }

    publishing {
        publications {
            create<MavenPublication>("maven") {
                groupId = group.toString()
                artifactId = "keyforge"
                version = version.toString()

                from(components["java"])
            }
        }
    }
}